= Zero-downtime rolling update deployments with Istio

// For more information see the following article series

== Running the example

- Build the project via Maven (`mvn clean package`).
- Build and push a Docker image to a registry of your choice.
- Change some behavior and re-build the project and Docker image with another Docker tag and re-push the image.
- Change the image definition in `deployment/coffee-shop/deployment.tpl.yaml`
- Change the IP address definition in service-entry to the public IP address of your ingress gateway.
- Apply `deployment/coffee-shop/{gateway,service,service-entry}.yaml` to your Istio cluster.
- Run `deployment/deploy-v1-istio.sh`
- Test the running version
- Run `deployment/exec-zero-downtime.sh <old-version> <new-version> <new-image>` to perform a deployment using version subsets (`v1`, `v2`, etc.).
- Deploy `deployment/fortio/deployment.yaml`, run `kubectl port-forward <fortio-pod> 8080:8080`, and run `./curl-test.sh` or `./load-test.sh` to test your application
- Browse `localhost:8080/fortio` to see the load test results.
- Execute a deployment during a load test and see what happens
